spring:
  application:
    name: mba-desafio-springai-pgvector
  
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.1
    vectorstore:
      pgvector:
        url: jdbc:postgresql://localhost:5432/rag
        username: postgres
        password: postgres
        collection-name: ${PGVECTOR_COLLECTION:documentos}
  
  datasource:
    url: jdbc:postgresql://localhost:5432/rag
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    com.fullcycle.mba.desafio: DEBUG
    org.springframework.ai: DEBUG
